name: "Bug Report"
description: Report a bug.

body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Please provide a link to a minimal reproduction of the bug

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: other
    attributes:
      label: Anything else?
