token = "NTI1ODEwNDk1Nzg2MDU3NzU4.XB1xLw.K3p2QDVGy5v3zDlV9ZI4HI1trbg"

events = [
	"READY",
    "INTERACTION_CREATE",
	"MESSAGE_REACTION_ADD",
	"MESSAGE_REACTION_REMOVE",
	"MESSAGE_REACTION_REMOVE_ALL",
]

intents = [
	"GUILDS",
	"GUILD_MESSAGES",
	"GUILD_MESSAGE_REACTIONS",
	"DIRECT_MESSAGES",
]

[presence]
status = "dnd"

[prometheus]
address = ":4500"
endpoint = "/metrics"

[broker]
type = "redis"
group = "gateway"

[redis]
url = "redis:6379"
pool_size = 5
