version: "3.7"

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - 4500:4500
    expose:
      - 4500
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    expose:
      - 6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s

  database:
    container_name: database
    build: ./postgres
    volumes:
      - postgres:/data
    environment:
      POSTGRES_USER: "alexis"
      POSTGRES_PASSWORD: "012903"
      POSTGRES_DB: "alexis"
    ports:
      - 5432:5432

volumes:
  redis:
  postgres:
