name: Code Scanning

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  CodeQL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          submodules: true

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@312e093a1892bd801f026f1090904ee8e460b9b6 # v2
        with:
          languages: typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@312e093a1892bd801f026f1090904ee8e460b9b6 # v2
