name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    name: Linting NodeJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Use Node.js v16
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: 16
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm lint

  Building:
    name: Building NodeJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          submodules: true
      - name: Use Node.js v16
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: 16
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: pnpm install
      - name: Build code
        run: pnpm build
